[workspace]
resolver = "2"
members = ["interface", "program"]

[workspace.metadata.cli]
solana = "1.18.15"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
format = "1.78.0"
lint = "1.78.0"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/febo/token"

[workspace.dependencies]
bytemuck = { version="1.18.0", features=["derive"] }
pinocchio = { git = "https://github.com/febo/pinocchio.git", branch = "febo/floating" }
pinocchio-pubkey = { git = "https://github.com/febo/pinocchio.git", branch = "febo/floating" }